version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: dev_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "Pubber"
    ports:
      - "5432:3306"
