spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pubber-db.cjadnl3hture.eu-north-1.rds.amazonaws.com:3306/Pubber?useUnicode=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}